<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="137340" started-at="2019-10-26T14:50:56Z" finished-at="2019-10-26T14:53:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="137340" started-at="2019-10-26T14:50:56Z" finished-at="2019-10-26T14:53:14Z">
      <class name="Frame.Framework.testclass">
        <test-method status="PASS" signature="OpenBrowser()[pri:0, instance:Frame.Framework.testclass@491cc5c9]" name="OpenBrowser" is-config="true" duration-ms="48096" started-at="2019-10-26T14:50:56Z" finished-at="2019-10-26T14:51:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method status="PASS" signature="LoginToApp()[pri:0, instance:Frame.Framework.testclass@491cc5c9]" name="LoginToApp" is-config="true" duration-ms="53777" started-at="2019-10-26T14:51:45Z" finished-at="2019-10-26T14:52:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApp -->
        <test-method status="FAIL" signature="Run()[pri:0, instance:Frame.Framework.testclass@491cc5c9]" name="Run" duration-ms="34859" started-at="2019-10-26T14:52:38Z" finished-at="2019-10-26T14:53:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at Generic.Excelib.getExceldata(Excelib.java:33)
at ObjRepo.Empdetails.detail_Add(Empdetails.java:27)
at Frame.Framework.testclass.Run(testclass.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Run -->
      </class> <!-- Frame.Framework.testclass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
